# Generated by Django 4.2.3 on 2023-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
